name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-test:
    name: "Run test"
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: zip
        shell: bash
        run: |
          tar -cvzf demo_dir.tar.gz demo_dir

      - name: Upload to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "demo_dir"
          path: "demo_dir.tar.gz"

  publish:
    name: "Publish"
    runs-on: macos-12
    needs:
      - run-test

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        name: "Download demo_dir"
        with:
          name: "demo_dir"
          path: ./demo_dir_cached
      - name: zip
        shell: bash
        run: |
          ls -lh
          ls demo_dir_cached
          mkdir ./unzipped
          tar -xf ./demo_dir_cached/demo_dir.tar.gz --directory ./unzipped
          ls -lh
          ls ./unzipped